FROM node:22-slim

LABEL org.opencontainers.image.authors="Muhammad Shahnewaz"


WORKDIR /app

# pnpm setup (pinned for CI stability)
RUN corepack enable && corepack prepare pnpm@10.11.0 --activate

# dependency layer
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# source code
COPY . .

# build step (main CI check)
RUN pnpm build