services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    container_name: express-auth-app-dev
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      DATABASE_URL: postgresql://${PG_USER}:${PG_PASSWORD}@postgres:${PG_PORT}/${PG_DATABASE}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: unless-stopped
    networks:
      - express-auth-network

  postgres:
    image: postgres:17
    container_name: express-auth-postgres-dev
    env_file:
      - .env
    ports:
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - express-auth-network

volumes:
  pgdata:
    name: express-auth-pgdata-dev

networks:
  express-auth-network:
    name: express-auth-network-dev
    driver: bridge
